version: "3.5"

services:

  datascience-tools:
    build:
      context: .
      dockerfile: Dockerfile
    image: flaviostutz/datascience-tools:2.9.0
    ports:
      - 8888:8888
      - 6006:6006
    # volumes:
    #   - /notebooks:/notebooks
    environment:
      - JUPYTER_TOKEN=flaviostutz
