version: "3"

services:

  datascience-tools-gpu:
    build:
      context: .
      dockerfile: Dockerfile-gpu
    image: flaviostutz/datascience-tools:1.0.0-gpu
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - /notebooks:/notebooks
    environment:
      - PASSWORD=flaviostutz
