version: "3"

services:

  cpu:
    build:
      context: .
      dockerfile: Dockerfile
    image: flaviostutz/datascience-tools:1.12.0
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - /notebooks:/notebooks
    environment:
      - PASSWORD=flaviostutz

  gpu:
    build:
      context: .
      dockerfile: Dockerfile-gpu
    image: flaviostutz/datascience-tools:1.0.0-gpu
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - /notebooks:/notebooks
    environment:
      - PASSWORD=flaviostutz
