version: "3.5"

services:

  datascience-tools-gpu:
    build:
      context: .
      dockerfile: Dockerfile-gpu
    image: flaviostutz/datascience-tools:2.9.0-gpu
    ports:
      - 8888:8888
      - 6006:6006
    # volumes:
    #   - /notebooks:/notebooks
    environment:
      - JUPYTER_PASSWORD=flaviostutz
