version: "3"

services:

  datascience-tools:
    build:
      context: .
      dockerfile: Dockerfile
    image: flaviostutz/datascience-tools:2.4.1
    ports:
      - 8888:8888
      - 6006:6006
    # volumes:
    #   - /notebooks:/notebooks
    environment:
      - PASSWORD=flaviostutz
      - SPARK_MASTER=spark-master
